runtime: custom
env: flex

entrypoint: streamlit run main.py --server.port=$PORT
service_account: streamlit-deployer@fraud-detection-new.iam.gserviceaccount.com

instance_class: F2

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

network:
  session_affinity: true
