service: fastapi
runtime: custom
env: flex

entrypoint: uvicorn app:app --host=0.0.0.0 --port=$PORT

service_account: fastapi-deployer@fraud-detection-new.iam.gserviceaccount.com

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10
