name: Deploy to GCP App Engine (FastAPI)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: fraud-detection-464016
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Install App Engine Python component
      run: |
        sudo apt-get update
        sudo apt-get install google-cloud-cli-app-engine-python

    - name: Deploy to App Engine
      run: gcloud app deploy --quiet
