name: Deploy Streamlit to App Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Streamlit App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Set up Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set project
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Install gcloud App Engine
        run: gcloud components install app-engine-python

      - name: Change to Streamlit directory
        working-directory: Streamlit_app
        run: |
          pip install -r requirements.txt
          gcloud app deploy --quiet
