name: Deploy Streamlit to GCP

on:
  push:
    paths:
      - 'Streamlit_app/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Decode Streamlit service account key
        run: echo "${{ secrets.STREAMLIT_SA_KEY }}" | base64 --decode > streamlit-key.json

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.STREAMLIT_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Deploy Streamlit to App Engine
        run: |
          cd Streamlit_app
          gcloud auth activate-service-account --key-file=../streamlit-key.json
          gcloud app deploy --quiet
