# .github/workflows/deploy.yml
name: CI/CD - Deploy FastAPI and Streamlit to GCP

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up gcloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Set project
      run: gcloud config set project ${{ secrets.GCP_PROJECT }}

    - name: Deploy FastAPI service
      run: |
        cd FastAPI
        gcloud app deploy --quiet

    - name: Deploy Streamlit service
      run: |
        cd ../Streamlit_app
        gcloud app deploy --quiet
